name             "vbox-guest-additions"
maintainer       "Jesús Torres"
maintainer_email "jmtorres@ull.es"
license          "BSD"
description      "Installs and configures VirtualBox Guest Additions"
