name             "ubuntu-desktop"
maintainer       "Jesús Torres"
maintainer_email "jmtorres@ull.es"
license          "BSD"
description      "Installs and configures Ubuntu for use as a desktop computer"
