name             "videovigilancia-devel"
maintainer       "Jesús Torres"
maintainer_email "jmtorres@ull.es"
license          "BSD"
description      "Installs 'Videovigilancia' project specific development tools"
